config/routes.rb
PiBase::Application.routes.draw do
  devise_for :users

  resources :spaces do
    get :related
    get :proofs
  end

  resources :properties do
    get :related
  end

  resources :traits, except: [:delete] do
    get :related
    collection { get :available }
  end

  resources :theorems, except: [:delete] do
    get :related
  end

  resources :users, only: [:show]

  get 'search',  to: 'formulae#search'
  get 'suggest', to: 'formulae#suggest'

  [:unproven, :errata, :help].each do |action|
    get action, to: "application##{action}"
  end
  root to: 'application#root'
end

app/models/space.rb
class Space < ActiveRecord::Base
  has_paper_trail only: [:name, :description]

  validates :name, :description, presence: true

  has_many :traits, dependent: :destroy

  include Search

  def self.by_formula fs
    ids = fs.map { |f, val| Formula.load(f).spaces(val) }.inject &:&
    Space.find ids
  end

  def to_s
    name
  end

  def proof_tree
    Proof::Tree.new self
  end
  cache_method :proof_tree

  def available
    ids = traits.pluck :property_id
    Property.where('id NOT IN (?)', ids).pluck :name
  end
end

app/controllers/spaces_controller.rb
class SpacesController < ObjectsController
  @object_class = Space

  def related
    deduced, direct = @space.traits.
      includes(:property, :value).
      sort_by { |t| t.property.name }.
      partition { |t| t.deduced? }

    render json: {
      "Manually Added"          => direct,
      "Automatically Generated" => deduced,
      "Needing Proofs"          => direct.select(&:unproven?)
    }
  end

  def proofs
    @space = Space.find params[:space_id]
    respond_to do |format|
      format.html
      format.json { render json: @space.proof_tree }
    end
  end

  private #-----

  def update_params
    params.require(:space).permit :name, :description, :proof_of_topology
  end
end

app/views/spaces/_form.html.slim
= form_for @space do |f|
  - if @space.errors.any?
    #error_explanation
      h2 = "#{pluralize(@space.errors.count, "error")} prohibited this space from being saved:"
      ul
        - @space.errors.full_messages.each do |message|
          li = message

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'

  = render 'objects/description', f: f
  = render 'objects/description', f: f, field: :proof_of_topology

  .actions = f.submit 'Save', class: 'btn btn-primary'

app/views/spaces/edit.html.slim
= link_to 'Back', :back, class: 'btn btn-default'
- if can? :manage, @space
  = link_to 'Delete', @space, class: 'btn btn-danger', confirm: 'Are you sure?', method: :delete

h1 Editing '#{@space.name}'

= render 'form'

app/views/spaces/index.html.slim
h3
  | #{Space.count} Spaces 
  - if can? :create, Space
    = link_to 'New', new_space_path, class: 'btn btn-mini btn-default'

= render 'application/definitions', list: @spaces

app/views/spaces/new.html.slim
= link_to 'Back', :back, class: 'btn btn-default'

h1 New Space

= render 'form'

app/views/spaces/proofs.html.slim
h1
  = link_to @space.name, @space
#proofs_pane.well
  .row
    #svg_pane.col-md-8
      h1.loading
        ' Loading
        i.icon-spinner.icon-spin

    #info_pane.col-md-4
      .key
        h5 Proof Explorer Key
        svg
          circle.node r=10 cx=12 cy=12 fill='#1f77b4'
          text x=28 y=16
            | Manually added property P
          circle.node r=6  cx=12 cy=38 fill='#1f77b4'
          text x=28 y=42
            | Follows directly from P
          circle.node r=6  cx=12 cy=62 fill='#202020'
          text x=28 y=66
            | Automatically deduced
        p Mouse over a node to preview it.
      hr
      .content

= onload do
  | new pi_base.ProofExplorer().render("#svg_pane");

app/views/spaces/show.html.slim
- content_for(:title) { @space.name }

h1
  = @space.name
  '
  = link_to 'Explore', space_proofs_path(@space), class: 'btn btn-mini btn-success'
  '
  = link_to 'Edit', edit_space_path(@space), class: 'btn btn-mini btn-default'

.well
  = markdown @space.description
  hr
  h4 Proof of Topology
  = markdown @space.proof_of_topology

#traits
= onload do
  | new pi_base.RelatedTraits('#traits');