config/routes.rb
PiBase::Application.routes.draw do
  devise_for :users

  resources :spaces do
    get :related
    get :proofs
  end

  resources :properties do
    get :related
  end

  resources :traits, except: [:delete] do
    get :related
    collection { get :available }
  end

  resources :theorems, except: [:delete] do
    get :related
  end

  resources :users, only: [:show]

  get 'search',  to: 'formulae#search'
  get 'suggest', to: 'formulae#suggest'

  [:unproven, :errata, :help].each do |action|
    get action, to: "application##{action}"
  end
  root to: 'application#root'
end

app/models/theorem.rb
class Theorem < ActiveRecord::Base
  has_paper_trail only: [:description]

  include Search

  # ----------

  serialize :antecedent, Formula
  serialize :consequent, Formula

  validates :antecedent, :consequent, :description, presence: true

  def formulae_are_valid
    [:antecedent, :consequent].each do |f|
      begin
        Formula.load send f
      rescue => e
        errors.add f, "could not be parsed as a formula: #{e}"
      end
    end
  end
  validate :formulae_are_valid

  def has_no_counterexamples
    unless counterexamples.empty?
      errors.add :consequent, "has a counterexample: #{counterexamples.first}"
    end
  rescue Formula::ParseError => e
    # Will be handled by another validation
  end
  validate :has_no_counterexamples

  # ----------

  has_many :proofs, dependent: :destroy
  has_many :traits, through: :proofs

  # ----------

  has_many :theorem_properties, dependent: :destroy
  has_many :properties, through: :theorem_properties

  def associate_properties!
    [antecedent.atoms, consequent.atoms].flatten.map(&:property).uniq.each do |p|
      TheoremProperty.where(theorem: self, property: p).create!
    end
  end
  after_create :associate_properties!

  # ----------

  scope :unproven, -> { where description: '' }

  # ----------

  def self.assert! formula, description: ""
    a,c = formula.split('=>').map { |f| Formula.parse_text f.strip }
    t = create! antecedent: a, consequent: c, description: description
    TheoremExploreJob.new.async.perform t.id
    t
  end

  # ----------

  def name
    "#{antecedent} ⇒ #{consequent}"
  end
  cache_method :name

  def to_s; name; end

  # ----------

  def contrapositive
    # FIXME: make an explict reason why these can never be saved over the original
    @contrapositive ||= ((~consequent) >> ~antecedent).tap { |t| t.id = id }
  end

  def converse
    @converse ||= consequent >> antecedent
  end

  def examples
    @examples ||= Space.by_formula antecedent => true, consequent => true
  end

  def counterexamples
    @counterexamples ||= Space.by_formula antecedent => true, consequent => false
  end

  def apply space
    assumptions = antecedent.verify(space) or return
    consequent.force space, assumptions, self, assumptions.length
  rescue ActiveRecord::RecordInvalid
    # Presumably because it violates the uniqueness constraint, and so already exists
    nil
  end

  # -- Exploration tools --

  def candidates
    Space.by_formula antecedent => true, consequent => nil
  end

  def explore
    # FIXME: make sure this returns the right stuff
    added =  candidates.map                { |s| apply s }
    added += contrapositive.candidates.map { |s| contrapositive.apply s }
    added.compact
  end

  def fix_theorem_properties!
    real = [antecedent, consequent].map do |f|
      f.atoms.map { |a| a.property.id }
    end.flatten.uniq.sort

    pids = theorem_properties.map(&:property_id).sort
    if pids != real
      theorem_properties.delete_all
      real.each { |pid| theorem_properties.create! property_id: pid }
    end
  end
end

app/controllers/theorems_controller.rb
class TheoremsController < ObjectsController
  @object_class = Theorem

  def index
    @theorems = Theorem.paginate page: params[:page], per_page: 15
  end

  def show
    @converse_counters = @theorem.converse.counterexamples
  end

  def related
    traits = @theorem.traits.
      includes(:space, :property, :value).
      sort_by { |t| [t.space.name, t.property.name] }

    render json: { "Implied" => traits }.as_json(add_space: true)
  end

  private #-----

  def create_params
    params.require(:theorem).permit :description, :antecedent, :consequent
  end

  def set_object
    super
    @theorem = TheoremDecorator.new @theorem
  end
end

app/views/theorems/edit.html.slim
= link_to 'Back', :back, class: 'btn btn-default'

h1 
  | Editing '
  = @theorem.linked_name.html_safe
  | '

= form_for @theorem do |f|
  - if @theorem.errors.any?
    #error_explanation
      h2 = "#{pluralize(@theorem.errors.count, "error")} prohibited this theorem from being saved:"
      ul
        - @theorem.errors.full_messages.each do |message|
          li = message

  = render 'objects/description', f: f

  .actions = f.submit 'Save', class: 'btn btn-primary'

app/views/theorems/index.html.slim
h3
  | #{Theorem.count} Theorems 
  - if can? :create, Theorem
    = link_to 'New', new_theorem_path, class: 'btn btn-mini btn-default'

= render 'application/definitions', list: @theorems

app/views/theorems/new.html.slim
= link_to 'Back', :back, class: 'btn btn-default'

h1 New Theorem

= form_for @theorem do |f|
  - if @theorem.errors.any?
    #error_explanation
      h2 = "#{pluralize(@theorem.errors.count, "error")} prohibited this theorem from being saved:"
      ul
        - @theorem.errors.full_messages.each do |message|
          li = message

  .control-group
    = f.label :antecedent
    .controls
      = f.text_field :antecedent, class: 'span12', autocomplete: 'off'
  .control-group
    = f.label :consequent
    .controls
      = f.text_field :consequent, class: 'span12', autocomplete: 'off'

  = render 'objects/description', f: f

  .actions = f.submit 'Save', class: 'btn btn-primary'

= onload do
  | var props = #{Property.pluck(:name).to_json.html_safe}
  |   , vals  = #{Value.pluck(:name).to_json.html_safe};
  | new pi_base.FormulaTypeahead('#theorem_antecedent', props, vals);
  | new pi_base.FormulaTypeahead('#theorem_consequent', props, vals);

app/views/theorems/show.html.slim
- content_for(:title) { @theorem.name }

h1
  = @theorem.linked_name.html_safe
  |  
  = link_to 'Edit', edit_theorem_path(@theorem), class: 'btn btn-mini btn-default'

.well
  - if @theorem.description.empty?
      p
        | Unfortunately, this Theorem was added without a proof to support it. You can help by 
        = link_to 'adding one', edit_theorem_path(@theorem)
        | . 
      p
        | You can 
        em really 
        | help by winnowing down the 
        = link_to 'list of all unsupported objects', unproven_path
        | .
  - else
    = markdown @theorem.description

- if @converse_counters.any?
  p This implication does not reverse, as evidenced by
  ul
    - if @converse_counters.length > 4
      - @converse_counters.first(3).each do |ex|
        li= link_to ex.name, ex
      li and #{@converse_counters.length - 3} others
    - else
      - @converse_counters.each do |ex|
        li= link_to ex.name, ex

#traits
= onload do
  | new pi_base.RelatedTraits('#traits');