config/routes.rb
PiBase::Application.routes.draw do
  devise_for :users

  resources :spaces do
    get :related
    get :proofs
  end

  resources :properties do
    get :related
  end

  resources :traits, except: [:delete] do
    get :related
    collection { get :available }
  end

  resources :theorems, except: [:delete] do
    get :related
  end

  resources :users, only: [:show]

  get 'search',  to: 'formulae#search'
  get 'suggest', to: 'formulae#suggest'

  [:unproven, :errata, :help].each do |action|
    get action, to: "application##{action}"
  end
  root to: 'application#root'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to new_user_session_url, alert: exception.message
  end

  def root
  end

  def help
  end

  def errata
    pairs = [[73, 10], [13, 54], [14, 54], [108, 20], [29, 54], [97, 54]]
    @traits = pairs.map { |s, p| Trait.where(space_id: s, property_id: p).first }
  end

  def unproven
    @theorems = Theorem.unproven.paginate page: params[:theorems], per_page: 15
    @traits   = Trait.unproven.paginate   page: params[:traits],   per_page: 30
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def onload
    content_for :onload do
      yield
    end
  end

  def bootstrap_will_paginate list, opts={}
    opts[:renderer] = BootstrapPagination::Rails
    will_paginate list, opts
  end

  def markdown text
    # FIXME: better XSS protection with spec
    # FIXME: scan the string and escape contextually depending on if we're in math tags
    text = h text
    text.gsub! '_', '\_'
    text.gsub! '\{', '\\\\\{'
    text.gsub! '\}', '\\\\\}'
    Markdown.render(text).html_safe
  end

  def typeahead form, klass, opts={}
    opts['autocomplete']  = 'off'
    opts['data-provide']  = 'typeahead'
    opts['data-source'] ||= klass.pluck(:name).to_json
    form.text_field klass.name.downcase, opts
  end

  def example_search str
    link_to str, search_path(q: str)
  end

  def flash_class name
    # Translate rails conventions to bootstrap conventions
    return :success if name == :notice
    return :error   if name == :alert
    return name
  end

  def icon name
    "<i class='icon-#{name}'></i>".html_safe
  end

  def word_diff version
    # FIXME: what about name changes?
    from, to = version.changeset[:description].map { |s| h(s) }
    Differ.diff_by_word(to, from).format_as(:html).html_safe
  rescue
    version.reify.description rescue nil
  end
end

app/views/application/_definitions.html.slim
= bootstrap_will_paginate list

dl#definitions
  - list.each do |item|
    dt= link_to item.name, item
    dd= markdown truncate item.description, length: 250, separator: ' '

javascript:
  pi_base.render_latex('definitions');

app/views/application/_markdown_help.html.slim
span.help-block #{link_to 'Markdown', 'http://daringfireball.net/projects/markdown/syntax'} syntax is supported

app/views/application/errata.html.slim
h1 
  | Errata 
  small to Counterexamples in Topology

p As noted in #{link_to 'the FAQ', help_path}, this site deliberately diverges from Counterexamples in Topology in its definition of the separation axioms.

p Aside from those defitions, the following values differ from the table in the back of Counterexamples.

dl
  - @traits.each do |t|
    dt= link_to "#{t.space.name}: #{t.name}", t
    - if t.deduced?
      dd= render 'traits/proof', trait: t
    - else
      dd= markdown t.description

app/views/application/help.html.slim
h1 FAQ

.alert.alert-info
  p I actually haven't gotten all that many questions yet, so there's a good chance yours isn't on this list. If not, #{link_to 'email me', 'mailto:jamesdabbs+pi-base@gmail.com'} and I'll be glad to help.

h3 Can I get a copy of the data?
p Sure. One of the #{link_to 'planned features', 'https://github.com/jamesdabbs/pi-base/issues'} is to include an API for getting what you want yourself, but until then, just #{link_to 'shoot me an email', 'mailto:jamesdabbs+pi-base@gmail.com'} telling me what you need and what you're planning on using it for.

h3 What does "Regular" mean?
p I was loathe to have to choose sides in this old debate, but I had to come down on one side of the fence. On this site, separation axioms are defined the way I learned them, e.g. such that \(T_{n+1} \implies T_n\) for \(n=0 \dots 4\).

h3 Which axioms are you assuming?
p There are #{link_to 'long term plans', 'https://github.com/jamesdabbs/pi-base/issues/16'} to support other important models, but for now ZFC is assumed throughout.

h3 What if I spot an error?
p Any user can edit the text description of an object or proof; if you spot an error there (or just want to improve the existing text), feel free to sign up and make the changes yourself.

p Because traits in the database are so strongly interconnected, only admins can alter the truthiness of a trait. If you spot a trait with an erroneous value, please #{link_to 'contact me', 'mailto:jamesdabbs+pi-base@gmail.com'} so that I can correct it.

p If you're comparing the data on this site to the table from Counterexamples in Topology, you should note a few #{link_to 'errata', errata_path}.

app/views/application/root.html.slim
.hero-unit
  h1 
    | Welcome to the 𝜋-Base
  p 
    ' A
    strong community maintained 
    ' database of topological examples featuring automated deduction and #{link_to 'powerful search', search_path(q: 'Compact + Connected + $T_2$ + ~Metrizable')}.

.alert.alert-info
  | This site is under active development. Get involved on 
  = link_to 'GitHub', 'https://github.com/jamesdabbs/pi-base'
  |  .

h3 For Researchers
p Suppose you are interested in a property #{link_to 'P', property_path(61)} and have shown that #{link_to 'Perfectly Normal', property_path(15)} ⇒ P, #{link_to 'CCC', property_path(29)} ⇒ P, and P ⇒ #{link_to 'Completely Regular', property_path(12)}. Here, you simply #{link_to 'add', theorem_path(127)} #{link_to 'those', theorem_path(128)} #{link_to 'theorems', theorem_path(126)}, let the site deduce what it can about the #{link_to 'spaces', spaces_path} it knows, and then #{link_to 'search', search_path} for spaces where P is still indeterminate. This streamlines time-consuming literature study and allows researchers to benefit from pooling their knowledge of exotic examples.

h3 For Students
p Every piece of information in the database should be traceable back to first principles, so students can #{link_to 'search for an interesting example', search_path(q: 'First Countable + Separable + ~Second Countable')} and then follow along with deriving its properties. Admittedly, there are currently #{link_to 'several traits missing proofs', unproven_path} - consider those your homework assignment.

hr

p &copy; #{link_to 'James Dabbs', 'http://jdabbs.com'} 2012 - #{Time.now.year}

app/views/application/unproven.html.slim
h3 Theorems
= bootstrap_will_paginate @theorems, param_name: :theorems
ul
  - @theorems.each do |theorem|
    li= link_to theorem.name, theorem

h3 Traits
= bootstrap_will_paginate @traits, param_name: :traits
ul
  - @traits.each do |trait|
    li= link_to "#{trait.space}: #{trait.name}", trait