config/routes.rb
PiBase::Application.routes.draw do
  devise_for :users

  resources :spaces do
    get :related
    get :proofs
  end

  resources :properties do
    get :related
  end

  resources :traits, except: [:delete] do
    get :related
    collection { get :available }
  end

  resources :theorems, except: [:delete] do
    get :related
  end

  resources :users, only: [:show]

  get 'search',  to: 'formulae#search'
  get 'suggest', to: 'formulae#suggest'

  [:unproven, :errata, :help].each do |action|
    get action, to: "application##{action}"
  end
  root to: 'application#root'
end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? "#{yield :title} | 𝜋-Base" : "𝜋-Base"
    = csrf_meta_tags

    = javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"
    = javascript_include_tag "//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"
    = javascript_include_tag "application"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = javascript_include_tag "http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
    javascript:
      MathJax.Hub.Config({
        tex2jax: {
          inlineMath: [ ['$','$'], ['\\(','\\)'] ]
        }
      });
    = stylesheet_link_tag "//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css"
    = stylesheet_link_tag "//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css"
    = stylesheet_link_tag "application", media: "all"

  body
    nav.navbar.navbar-default
      .container
        .navbar-header
          = link_to "𝜋-Base", root_path, class: :"navbar-brand"

        .collapse.navbar-collapse
          ul.nav.navbar-nav
            li= link_to "Spaces", spaces_path
            li= link_to "Properties", properties_path
            li= link_to "Traits", traits_path
            li= link_to "Theorems", theorems_path
            li= link_to "Search", search_path
          ul.nav.navbar-nav.pull-right
            - if current_user
              li= link_to "#{icon('user')} #{current_user.email}".html_safe, user_path(current_user)
              li= link_to "Logout", destroy_user_session_path, method: :delete
            - else
              li= link_to "Login", new_user_session_path
              li= link_to "Register", new_user_registration_path
            li= link_to icon('question-sign'), help_path

    - if content_for? :uncontained
      .uncontained
        = yield :uncontained


    .container
      noscript
        div class="alert alert-notice"
          h4 Javascript Disabled!
          p It looks like Javascript is disabled in your browser. Some features on this site will not work correctly unless you re-enable it. #{link_to "Click here", "http://www.enable-javascript.com/"} for more information.
      
      .flash
        - flash.each do |name, msg|
          div class="alert alert-#{flash_class name}"
            a.close data-dismiss="alert"
              | &times;
            div id="flash_#{flash_class name}"
              = msg

      = yield

      = yield :scripts

      javascript:
        $(function() {
          #{yield :onload}
        })